services:
  webapi:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "5001:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=db;Database=admin_auth_system;Username=postgres;Password=10Student
    depends_on:
      - db

  db:
    image: postgres:latest
    ports:
      - "5434:5432"
    environment:
      - POSTGRES_DB=admin_auth_system
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=10Student
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: